# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARYouThereYet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlamofireImage', '~>3.3'

  pod 'MapboxARKit', :git => 'https://github.com/mapbox/mapbox-arkit-ios.git'
  
  # Pods for ARYouThereYet

  target 'ARYouThereYetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARYouThereYetUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
